### ISSUE TITLE
[功能询问]关于修改字体

### ISSUE THREAD

**Issue by OcrSu** [Lhcfl/hexo-theme-anatolo#33]
我已经在style.styl中修改了站点字体，但是
![image](https://github.com/user-attachments/assets/e00786ee-cd30-458f-bfa9-00710130bd96)

代码块中的字体我没有找到修改的位置。

请问这里面的字体该如何修改？🙏

**Comment by Lhcfl** [comment]
在 `blog_basic.scss` 的第二行

```scss
:root {
  --mono-font-face: 'mononoki', 'Consolas', 'Roboto Mono', 'Lucida Console', 'Trebuchet MS', 'Courier New', 'courier',
    monospace;
}
```
