### ISSUE TITLE
[feature] 可以增加一个开关控制进入首页看到的是文章或者是目录吗？

### ISSUE THREAD

**Issue by eeetechen** [Lhcfl/hexo-theme-anatolo#35]
特别喜欢这个主题，翻看文档的时候发现auth已经切换了。
希望增加的功能：
首页样式修改，是那种一言，一句看起来不明觉厉的话。
或者进来就是目录，如果一进来就是一篇文章的话，有点太快了。
然后这个首页的显示可配置为文章或者目录，使用_config.yaml来控制。

或者，在这个issue底下告诉我应该修改哪些文件可以达到这个效果。我可以尝试与AI一起修改。

真的很遗憾，听到你不维护这个主题。

**Comment by Lhcfl** [comment]
`layout/index.pug` 控制首页的主要区域的渲染，`layout/partial/sidebar.pug` 控制所有页面的侧边栏的渲染，你可以考虑修改这些文件达成你想要的效果

**Comment by eeetechen** [comment]
ty

**Comment by eeetechen** [comment]
除了这个，还有 “关于” 以及 “友链” 界面点进去现在是404.这个如何修改。我在layout里面看见了social_link看起来像友链，并且在sidebar也看到了引入了social_link 但不知道为什么没有起作用？
我的网站 https://blog.eeete.fun

**Comment by Lhcfl** [comment]
友链定义在 _config.yml

```yml
# Nav menu
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  About: /about
  Links: /links
```

需要你自己在 hexo 的 _source 文件夹里面建立 about.md 和 links.md 文件

social_link 是社交媒体链接的意思
